<html lang="en">

<head>
    <meta charset="utf-8">
    <title><?php

            use App\Http\Controllers\EApp;

            echo 'Online Voting Results'; ?></title>
    <style>
        .header,
        .footer {
            width: 100%;
            text-align: left;
            position: fixed;

        }

        .header {
            top: 0px;
        }

        .footer {
            bottom: -20px;
        }

        .pagenum:before {
            content: counter(page);
        }




        @page {
     
            size: 215.9mm 355.6mm;
            /* size: 279mm 216mm; */
        }

        @font-face {
            font-family: 'Roboto';
            src: url("{{ asset('fonts/Roboto-Bold.ttf') }}");
            font-weight: normal;
        }

        table {

            border-spacing: 0;
            width: 100%;
            border: 1px 1px 0px 1px;

        }

         td,
        th {
            border: 0.5px solid black;
            padding: 2px;
            font-size: 10px;
            text-align: center;
        }

        .text-left {
            text-align: left;
        }

        .page-break {
            page-break-after: always;
        }


        thead {
            background-color: #79AC78;
            color: white
        }


        tfoot {
            background-color: #D0E7D2;
        }
    </style>
</head>

<body style="font-family: 'Roboto', sans-serif;">


<!-- Footer section -->
<div class="footer">
    <div style="float: left;">
        Report generated by: {{ Auth::user()->adminAccount->firstName . " " . Auth::user()->adminAccount->lastName }} on {{ now()->format('Y-m-d H:i:s') }} ({{ config('app.timezone') }})
    </div>
    <div style="float: right;">
        Page <span class="pagenum"></span>
    </div>
    <div style="clear: both;"></div>
</div>



    <h2 style="text-align: center; margin-top: 10px; line-height: 1px">ONLINE VOTING RESULTS</h2>
    <h1 style="text-align: center;">2023 Annual Stockholders' Meeting and Election</h1>
    <h1>Masterlist</h1>
    <table>
        <thead>
            <tr>
                <th rowspan="2">Account No</th>
                <th rowspan="2">Stockholder</th>
                <th rowspan="2">Account Status</th>
                <th colspan="2">Stockholder Online</th>
                <th colspan="2">Proxy Voting</th>
 
            </tr>
            <tr>
             
                <th>BOD</th>
                <th>Amendment</th>
                <th>BOD</th>
                <th>Amendment</th>
            </tr>
        </thead>
        <tbody>
            
            <?php

                $totalOnlineBod = 0;
                $totalOnlineAmendment = 0;
                $totalProxyBod = 0;
                $totalProxyAmendment = 0;
                $totalDelinquent = 0;

                foreach($accounts as $account) {

                    $bodOnline = '';
                    $bodProxy = '';
                    $amendmentOnline = '';
                    $amendmentProxy = '';


                    if($account->isDelinquent === 1) {
                        $totalDelinquent++;
                    }

                    if($account->usedBod !== null) {

                        if($account->usedBod->ballot->ballotType === 'person') {
                            $totalOnlineBod++;
                            $bodOnline = $account->usedBod->ballot->ballotNo;
                        }

                        else {
                            $totalProxyBod++;
                            $bodProxy = $account->usedBod->ballot->ballotNo;;
                        }

                    }


                    if($account->usedAmendment !== null) {

                         if($account->usedAmendment->ballot->ballotType === 'person') {
                            $totalOnlineAmendment++;
                            $amendmentOnline = $account->usedAmendment->ballot->ballotNo;
                        }

                        else {
                            $totalProxyAmendment++;
                            $amendmentProxy = $account->usedAmendment->ballot->ballotNo;;
                        }

                    }

                    echo '<tr>
                            <td>'.$account->accountKey.'</td>
                            <td>'.$account->stockholder->stockholder.'</td>
                            <td>' . ($account->isDelinquent === 1 ? 'delinquent' : '').'</td>
                            <td>'.$bodOnline.'</td>
                            <td>'.$amendmentOnline.'</td>
                            <td>'.$bodProxy.'</td>
                            <td>'.$amendmentProxy.'</td>
                            </tr>';
                }

            ?>
            
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td><?php echo $totalDelinquent; ?></td>
                <td><?php echo $totalOnlineBod; ?></td>
                <td><?php echo $totalOnlineAmendment; ?></td>
                <td><?php echo $totalProxyBod; ?></td>
                <td><?php echo $totalProxyAmendment; ?></td>
            </tr>
        </tfoot>
    </table>


    <h3>Delinquent Accounts with BOD Proxies</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Account</th>
                <th>Stockholder</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $counter = 0;
            
                foreach($delinquentAccountsWithBODProxies as $delWithProxy) {

                    $counter++;
                    echo '<tr>
                        <td>'.$counter.'</td>
                        <td>'.$delWithProxy->accountKey.'</td>
                        <td>'.$delWithProxy->stockholder->stockholder.'</td>
                    </tr>';

                  
                }


                $totalDelinquentBod = $counter;
            ?>


        </tbody>
    </table>


    <h3>DELINQUENT ACCOUNTS WITH AMENDMENT PROXIES</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Account</th>
                <th>Stockholder</th>
            </tr>
        </thead>
        <tbody>
            <?php
                $counter = 0;
                foreach($delinquentAccountsWithAmendmentProxies as $delWithProxy) {
                    $counter++;
                    echo '<tr>
                        <td>'.$counter.'</td>
                        <td>'.$delWithProxy->accountKey.'</td>
                        <td>'.$delWithProxy->stockholder->stockholder.'</td>
                    </tr>';

                   
                }


                $totalDelinquentAmendment = $counter;
            ?>
        </tbody>
    </table>

    <h3>TALLY FOR BOD PROXIES</h3>
    <table>
        <thead>
            <tr>
                <th>Count</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $bodProxyCount }}</td>
                <td style="text-align: left">TOTAL BOD PROXIES</td>
            </tr>
            <tr style="color: red">
                <td style="color: red">{{ $totalProxyBod }}</td>
                <td style="text-align: left">TOTAL USED BOD PROXIES</td>
            </tr>
            <tr style="color: red">
                <td style="color: red">{{ $totalDelinquentBod }}</td>
                <td style="text-align: left">TOTAL DELINQUENT ACCOUNT WITH BOD PROXIES</td>
            </tr>

            <tr style="color: red">
                <td style="color: red">{{ $revokedBod }}</td>
                <td style="text-align: left">TOTAL REVOKED</td>
            </tr>


        </tbody>
        
    </table>   
    <h3>TALLY FOR AMENDMENT PROXIES</h3>
    <table>
        <thead>
            <tr>
                <th>Count</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            
            <tr>
                <td>{{ $amendmentProxyCount }}</td>
                <td  style="text-align: left">TOTAL AMENDMENT PROXIES</td>
            </tr>
            <tr style="color: red">
                <td>{{ $totalProxyAmendment }}</td>
                <td  style="text-align: left">TOTAL USED AMENDMENT PROXIES</td>
            </tr>
            <tr style="color: red">
                <td>{{$totalDelinquentAmendment}}</td>
                <td  style="text-align: left">TOTAL DELINQUENT ACCOUNT WITH AMENDMENT PROXIES</td>
            </tr>

            
            <tr style="color: red">
                <td style="color: red">{{ $revokedAmendment }}</td>
                <td style="text-align: left">TOTAL REVOKED</td>
            </tr>
        </tbody>
        
    </table>  


    


</body>

</html>