<html lang="en">

<head>
    <meta charset="utf-8">
    <title><?php

            use App\Http\Controllers\EApp;
            use Illuminate\Support\Facades\Auth;

            echo 'Online Voting Results'; ?></title>
    <style>
        .header,
        .footer {
            width: 100%;
            text-align: left;
            position: fixed;
        }

        .header {
            top: 0px;
        }

        .footer {
            bottom: -20px;
        }

        .pagenum:before {
            content: counter(page);
        }




        @page {
            padding: 10px;
            size: 216mm 279mm;
        }

        @font-face {
            font-family: 'Roboto';
            src: url("{{ asset('fonts/Roboto-Bold.ttf') }}");
            font-weight: normal;
        }

        table {

            border-spacing: 0;
            width: 100%;
            border: 1px 1px 0px 1px;

        }

        td,
        th {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        .text-left {
            text-align: left;
        }

        tfoot td {
            border: 0px;
        }

        .page-break {
            page-break-after: always;
        }


        thead {
            background-color: #6b8e4e;
            color: white
        }
    </style>
</head>

<body style="font-family: 'Roboto', sans-serif;">


    <!-- Footer section -->
    <div class="footer">
        <div style="float: left; font-size: 10">
            Report generated by: {{ Auth::user()->adminAccount->firstName . " " . Auth::user()->adminAccount->lastName }} on {{ now()->format('Y-m-d H:i:s') }} ({{ config('app.timezone') }})
        </div>
        <div style="float: right;">
            Page <span class="pagenum"></span>
        </div>
        <div style="clear: both;"></div>
    </div>



    <h2 style="text-align: center; margin-top: 10px; line-height: 1px">ONLINE VOTING RESULTS</h2>



    <h1 style="text-align: center;">2024 Annual Stockholders' Meeting and Election</h1>

    @if(config('evoting.enableAmendment')===true)
    <h1>Amendments</h1>
    <table class="table">
        <thead>
            <tr>
                <th width="65%">Amendments</th>
                <th width="10%">Yes</th>
                <th width="10%">No</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php

            $totalYes = 0;
            $totalNo = 0;
            $totalAmendment = 0;

            foreach ($amendmentData as $amendment) {

                $totalYes = $totalYes + (int) $amendment->totalYes;
                $totalNo = $totalNo + (int) $amendment->totalNo;

                $amendmentSubtotal = $amendment->totalYes + $amendment->totalNo;
                $totalAmendment = $totalAmendment + $amendmentSubtotal;

                echo '<tr>
                            <td>' . $amendment->amendmentDesc . '</td>
                            <td>' . number_format($amendment->totalYes, 0) . '</td>
                            <td>' . number_format($amendment->totalNo, 0) . '</td>
                            <td style="">' . number_format($amendmentSubtotal, 0) . '</td>
                        </tr>';
            }

            echo '<tr style="font-weight: bold"><td>TOTAL</td><td>' . number_format($totalYes, 0) . '</td><td>' . number_format($totalNo, 0) . '</td><td>' . number_format($totalAmendment, 0) . '</td></tr>';

            if (count($amendmentData) === 0) {

                echo '<tr><td colspan="4" style="align: center">No record</td></tr>';
            }


            ?>
        </tbody>
        <tfoot>
            <?php

            ?>
        </tfoot>
    </table>
    @endif

    <br><br>

    <h1>Other Items in the Agenda</h1>
    <table class="table">
        <thead>
            <tr>
                <th style="width: 55%">Agenda</th>
                <th width="10%">Favor</th>
                <th width="10%">Not Favor</th>
                <th width="10%">Abstain</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php


            $totalFavor = 0;
            $totalNotFavor = 0;
            $totalAbstain = 0;

            $totalAgenda = 0;

            foreach ($agendaData as $agenda) {

                $totalFavor = $totalFavor + (int) $agenda->totalFavor;
                $totalNotFavor = $totalNotFavor + (int) $agenda->totalNotFavor;
                $totalAbstain = $totalAbstain + (int) $agenda->totalAbstain;

                $subtotalAgenda = (int) $agenda->totalFavor + (int) $agenda->totalNotFavor + (int) $agenda->totalAbstain;

                $totalAgenda = $totalAgenda + $subtotalAgenda;

                echo '<tr>
                        <td>' . $agenda->agendaDesc . '</td>
                        <td>' . number_format($agenda->totalFavor, 0) . '</td>
                        <td>' . number_format($agenda->totalNotFavor, 0) . '</td>
                        <td>' . number_format($agenda->totalAbstain, 0) . '</td>
                        <td>' . number_format($subtotalAgenda, 0) . '</td>
                    </tr>';
            }


            echo '<tr style="font-weight: bold"><td>TOTAL</td><td>' . number_format($totalFavor, 0) . '</td><td>' . number_format($totalNotFavor, 0) . '</td><td>' . number_format($totalAbstain, 0) . '</td><td>' . number_format($totalAgenda, 0) . '</td></tr>';

            if (count($agendaData) === 0) {
                echo '<tr><td colspan="4" style="align: center">No record</td></tr>';
            }
            ?>
        </tbody>
    </table>
    <div style="page-break-before: always;">
        <!-- Content of the first page -->
    </div>

    <h1 style="text-align: center">Board of Directors</h1>

    <h3>Regular</h3>
    <table class="table">
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="37%">Candidates</th>
                <th width="20%">Stockholder Online Voting</th>
                <th>Proxy Voting</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php

            $counter = 1;

            $totalStockholderOnline = 0;
            $totalProxyVoting = 0;

            foreach ($bodSummary as $bod) {

                if ($bod['candidateType'] === 'independent') {
                    continue;
                }

                $totalStockholderOnline = $totalStockholderOnline + (int) $bod['online'];
                $totalProxyVoting = $totalProxyVoting + (int) $bod['proxy'];



                echo '<tr>
                <td width="5%">' . $counter . '</td>
                            <td style="text-align: left">' . $bod['candidateName'] . '</td>
                            <td>' . number_format($bod['online'], 0) . '</td>
                            <td>' . number_format($bod['proxy'], 0) . '</td>
                            <td style="font-weight: bold">' . number_format($bod['total'], 0) . '</td>
                        </tr>';

                $counter++;
            }


            echo '<tr style="font-weight: bold"><td colspan="2">TOTAL</td><td>' . number_format($totalStockholderOnline, 0) . '</td><td>' . number_format($totalProxyVoting, 0) . '</td><td>' . (number_format($totalStockholderOnline + $totalProxyVoting, 0)) . '</td></tr>';


            if (count($bodSummary) === 0) {
                echo '<tr><td colspan="5" style="align: center">No record</td></tr>';
            }
            ?>

        </tbody>
    </table>
    <div style="page-break-before: always;">
        <h3>Independent</h3>
        <table>
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="37%">Candidates</th>
                    <th width="20%">Stockholder Online Voting</th>
                    <th>Proxy Voting</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php

                $counter = 1;

                $totalStockholderOnline = 0;
                $totalProxyVoting = 0;


                foreach ($bodSummary as $bod) {

                    if ($bod['candidateType'] === 'regular') {
                        continue;
                    }

                    $totalStockholderOnline = $totalStockholderOnline + (int) $bod['online'];
                    $totalProxyVoting = $totalProxyVoting + (int) $bod['proxy'];

                    echo '<tr>
                <td>' . $counter . '</td>
                            <td style="text-align: left">' . $bod['candidateName'] . '</td>
                            <td>' . number_format($bod['online'], 0) . '</td>
                            <td>' . number_format($bod['proxy'], 0) . '</td>
                            <td>' . number_format($bod['total'], 0) . '</td>
                        </tr>';

                    $counter++;
                }

                echo '<tr style="font-weight: bold"><td colspan="2">TOTAL</td><td>' . number_format($totalStockholderOnline, 0) . '</td><td>' . number_format($totalProxyVoting, 0) . '</td><td>' . (number_format($totalStockholderOnline + $totalProxyVoting, 0)) . '</td></tr>';



                if (count($bodSummary) === 0) {
                    echo '<tr><td colspan="5" style="align: center">No record</td></tr>';
                }
                ?>

            </tbody>
        </table>


        <span style="position: absolute; top: 435px; left: 50px; font-size: 11px">Verified by:</span>
        <span style="position: absolute; top: 430px; left: 270px; font-size: 11px">RELI GUECO</span>
        <span style="position: absolute; top: 430px; left: 520px; font-size: 11px">LYKA DIGGAY</span>

        <span style="position: absolute; top: 435px; left: 230px; font-size: 11px"> _________________________ </span>
        <span style="position: absolute; top: 435px; left: 480px; font-size: 11px"> ___________________________ </span>




        <span style="position: absolute; top: 448px; left: 190; font-size: 11px">INTERNAL AUDIT HEAD</span>
        <span style="position: absolute; top: 448px; left: 370; font-size: 11px">INTERNAL AUDIT ASSISTANT</span>











        <span style="position: absolute; top: 542px; left: 50px; font-size: 11px">Witnessed by:</span>
        <span style="position: absolute; top: 557px; left: 185; font-size: 11px">SGV REPRESENTATIVE</span>
        <span style="position: absolute; top: 557px; left: 375; font-size: 11px">SGV REPRESENTATIVE</span>
        <span style="position: absolute; top: 542px; left: 230px; font-size: 11px"> _________________________ </span>
        <span style="position: absolute; top: 542px; left: 480px; font-size: 11px"> ___________________________ </span>







        <p style="text-align: center; margin-top: 360px">COMELEC</p>

        <pre style="margin-left: 58px; margin-top: 50px">__________________     __________________      __________________</pre>
</body>

</html>